# Generated by Django 2.1.5 on 2019-01-27 15:20

from django.db import migrations


def create_data(apps, schema_editor):
    Player = apps.get_model('players', 'Player')
    Customer(first_name="Player 001", last_name="Schon", email="customer001@email.com", description= "Customer 001 description").save()

class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
