# Generated by Django 2.1.5 on 2019-01-27 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
    ]
